2023-03-17 18:30:50,649 INFO    MainThread:83239 [wandb_setup.py:_flush():68] Configure stats pid to 83239
2023-03-17 18:30:50,650 INFO    MainThread:83239 [wandb_setup.py:_flush():68] Loading settings from /home/tharikh/.config/wandb/settings
2023-03-17 18:30:50,650 INFO    MainThread:83239 [wandb_setup.py:_flush():68] Loading settings from /home/tharikh/dl-ass-1/wandb/settings
2023-03-17 18:30:50,650 INFO    MainThread:83239 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-03-17 18:30:50,650 INFO    MainThread:83239 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-17 18:30:50,650 INFO    MainThread:83239 [wandb_setup.py:_flush():68] Applying login settings: {'api_key': '***REDACTED***'}
2023-03-17 18:30:50,650 INFO    MainThread:83239 [wandb_setup.py:_flush():68] Applying login settings: {'api_key': '***REDACTED***'}
2023-03-17 18:30:50,650 INFO    MainThread:83239 [wandb_init.py:_log_setup():492] Logging user logs to /home/tharikh/dl-ass-1/wandb/run-20230317_183050-emzey5a3/logs/debug.log
2023-03-17 18:30:50,650 INFO    MainThread:83239 [wandb_init.py:_log_setup():493] Logging internal logs to /home/tharikh/dl-ass-1/wandb/run-20230317_183050-emzey5a3/logs/debug-internal.log
2023-03-17 18:30:50,650 INFO    MainThread:83239 [wandb_init.py:_jupyter_setup():438] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f9a070420a0>
2023-03-17 18:30:50,650 INFO    MainThread:83239 [wandb_init.py:init():532] calling init triggers
2023-03-17 18:30:50,651 INFO    MainThread:83239 [wandb_init.py:init():538] wandb.init called with sweep_config: {}
config: {}
2023-03-17 18:30:50,651 INFO    MainThread:83239 [wandb_init.py:init():554] re-initializing run, found existing run on stack: bmd6189g
2023-03-17 18:30:50,652 INFO    MainThread:83239 [wandb_run.py:_finish():1854] finishing run cs22m058/dl-project-final/bmd6189g
2023-03-17 18:30:50,652 INFO    MainThread:83239 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2023-03-17 18:30:50,652 INFO    MainThread:83239 [wandb_run.py:_restore():2066] restore
2023-03-17 18:30:50,653 INFO    MainThread:83239 [wandb_run.py:_restore():2072] restore done
2023-03-17 18:30:55,102 INFO    MainThread:83239 [wandb_init.py:init():588] starting backend
2023-03-17 18:30:55,103 INFO    MainThread:83239 [wandb_init.py:init():592] setting up manager
2023-03-17 18:30:55,105 INFO    MainThread:83239 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-03-17 18:30:55,107 INFO    MainThread:83239 [wandb_init.py:init():599] backend started and connected
2023-03-17 18:30:55,123 INFO    MainThread:83239 [wandb_run.py:_label_probe_notebook():1203] probe notebook
2023-03-17 18:30:55,123 INFO    MainThread:83239 [wandb_run.py:_label_probe_notebook():1213] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-03-17 18:30:55,123 INFO    MainThread:83239 [wandb_init.py:init():687] updated telemetry
2023-03-17 18:30:55,144 INFO    MainThread:83239 [wandb_init.py:init():727] communicating run to backend with 60.0 second timeout
2023-03-17 18:31:00,874 WARNING MainThread:83239 [wandb_init.py:init():1154] interrupted
Traceback (most recent call last):
  File "/home/tharikh/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1133, in init
    run = wi.init()
  File "/home/tharikh/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 730, in init
    result = run_init_handle.wait(
  File "/home/tharikh/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 273, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/home/tharikh/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 120, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/home/tharikh/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 116, in _wait
    return self._event.wait(timeout=timeout)
  File "/home/tharikh/anaconda3/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/home/tharikh/anaconda3/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2023-03-17 18:33:42,976 INFO    MainThread:83239 [wandb_settings.py:_apply_login():1566] Applying login settings: {'api_key': '***REDACTED***'}
2023-03-17 18:33:42,985 INFO    MainThread:83239 [wandb_settings.py:_apply_login():1566] Applying login settings: {'api_key': '***REDACTED***'}
2023-03-17 18:33:44,289 INFO    MainThread:83239 [pyagent.py:run():314] Starting sweep agent: entity=None, project=None, count=10000
