2023-03-17 16:58:54,679 INFO    MainThread:77949 [wandb_setup.py:_flush():68] Configure stats pid to 77949
2023-03-17 16:58:54,679 INFO    MainThread:77949 [wandb_setup.py:_flush():68] Loading settings from /home/tharikh/.config/wandb/settings
2023-03-17 16:58:54,679 INFO    MainThread:77949 [wandb_setup.py:_flush():68] Loading settings from /home/tharikh/dl-ass-1/wandb/settings
2023-03-17 16:58:54,679 INFO    MainThread:77949 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-03-17 16:58:54,679 INFO    MainThread:77949 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program': 'main.py'}
2023-03-17 16:58:54,680 INFO    MainThread:77949 [wandb_setup.py:_flush():68] Applying login settings: {'api_key': '***REDACTED***'}
2023-03-17 16:58:54,680 INFO    MainThread:77949 [wandb_setup.py:_flush():68] Applying login settings: {'api_key': '***REDACTED***'}
2023-03-17 16:58:54,680 INFO    MainThread:77949 [wandb_init.py:_log_setup():492] Logging user logs to /home/tharikh/dl-ass-1/wandb/run-20230317_165854-f1qvnv95/logs/debug.log
2023-03-17 16:58:54,680 INFO    MainThread:77949 [wandb_init.py:_log_setup():493] Logging internal logs to /home/tharikh/dl-ass-1/wandb/run-20230317_165854-f1qvnv95/logs/debug-internal.log
2023-03-17 16:58:54,680 INFO    MainThread:77949 [wandb_init.py:init():532] calling init triggers
2023-03-17 16:58:54,680 INFO    MainThread:77949 [wandb_init.py:init():538] wandb.init called with sweep_config: {}
config: {}
2023-03-17 16:58:54,680 INFO    MainThread:77949 [wandb_init.py:init():588] starting backend
2023-03-17 16:58:54,680 INFO    MainThread:77949 [wandb_init.py:init():592] setting up manager
2023-03-17 16:58:54,685 INFO    MainThread:77949 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-03-17 16:58:54,690 INFO    MainThread:77949 [wandb_init.py:init():599] backend started and connected
2023-03-17 16:58:54,696 INFO    MainThread:77949 [wandb_init.py:init():687] updated telemetry
2023-03-17 16:58:54,713 INFO    MainThread:77949 [wandb_init.py:init():727] communicating run to backend with 60.0 second timeout
2023-03-17 16:58:57,752 WARNING MsgRouterThr:77949 [router.py:message_loop():77] message_loop has been closed
2023-03-17 16:59:04,731 ERROR   MainThread:77949 [wandb_init.py:init():1160] error
Traceback (most recent call last):
  File "/home/tharikh/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1133, in init
    run = wi.init()
  File "/home/tharikh/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 730, in init
    result = run_init_handle.wait(
  File "/home/tharikh/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 271, in wait
    raise MailboxError("transport failed")
wandb.errors.MailboxError: transport failed
