
epoch: 0 => loss = 0.40954372490706387
epoch: 1 => loss = 0.36416690457229944
epoch: 2 => loss = 0.34016615542181317
epoch: 3 => loss = 0.322608627074525
epoch: 4 => loss = 0.30908847674699075
epoch: 5 => loss = 0.2979451137986872
epoch: 6 => loss = 0.28805618724446047
epoch: 7 => loss = 0.27890651756568746
epoch: 8 => loss = 0.2703179895079277
epoch: 9 => loss = 0.2623739861978204
Traceback (most recent call last):
  File "main.py", line 70, in <module>
    test_predict = nn.feedforward(X_test)
  File "/home/tharikh/dl-ass-1/network.py", line 90, in feedforward
    a = self.W[0].T @ X + self.b[0]
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 28 is different from 784)